export const FILTER_STATUS = {
    ALL:"all",
    ACTIVE:"active",
    COMPLETE:"complete"
}

export const ACTION = {
    ADD_TODO:"ADD_TASK",
    EDIT_TODO:"EDIT_TASK",
    DELETE_TODO:"DELETE_TASK",
    DELETE_COMPLETED_TODO:"DELETE_COMPLETED_TASKS",
    TOGGLE:"TOGLLE_TASK",
    CHANGE_TODO_STATUS:"CHANGE_STATUS"
}