export const FILTER_STATUS = {
    ALL:"all",
    ACTIVE:"active",
    COMPLETE:"complete"
}

export const ACTION = {
    ADD_TASK:"ADD_TASK",
    EDIT_TASK:"EDIT_TASK",
    DELETE_TASK:"DELETE_TASK",
    DELETE_COMPLETED_TASKS:"DELETE_COMPLETED_TASKS",
    TOGGLE:"TOGLLE_TASK",
    SHOW_EDIT_TASK_COUNT:"SHOW_EDIT_TASK_COUNT",
    CHANGE_TODO_STATUS:"CHANGE_STATUS"
}