export const FILTER_STATUS = {
    ALL:"ALL",
    ACTIVE:"ACTIVE",
    COMPLETE:"COMPLETE"
}

export const ACTION = {
    ADD_TODO:"ADD_TODO",
    EDIT_TODOS:"EDIT_TODOS",
    DELETE_TODOS:"DELETE_TODOS",
    DELETE_COMPLETED_TODOS:"DELETE_COMPLETED_TODOS",
    TOGGLE:"TOGLLE_TODO",
    UPDATE_FILTER:"UPDATE_FILTER",
    EDIT_TODO_ITEM:"EDIT_TODO_ITEM"
}